server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.springframework: INFO
    org.springframework.kafka: INFO
  file:
    name: logs/spring-boot-app.log
